version: "3.7"

networks:
  internal:
    name: internal
    driver: bridge

volumes:
  database:

services:
  database:
    image: timescale/timescaledb:latest-pg10
    networks: 
      - internal
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: polkadothub
      POSTGRES_PASSWORD: polkadothub
      POSTGRES_DB: polkadothub
    volumes:
      - database:/var/lib/postgresql/data/
  
  server:
    build: .
    command: -cmd=server
    networks:
      - internal
    ports:
      - "8081:8081"
    environment:
      PROXY_URL: localhost:50051
      DATABASE_DSN: postgres://polkadothub:polkadothub@database/polkadothub?sslmode=disable
    depends_on:
      - database
  
  worker:
    build: .
    command: -cmd=worker
    networks:    
      - internal
    environment:
      PROXY_URL: localhost:50051
      DATABASE_DSN: postgres://polkadothub:polkadothub@database/polkadothub?sslmode=disable
    depends_on:
      - database

  migrate:
    build: .
    command: -cmd=migrate
    networks:
      - internal
    environment:
      PROXY_URL: localhost:50051
      DATABASE_DSN: postgres://polkadothub:polkadothub@database/polkadothub?sslmode=disable
    depends_on:
      - database

  migrate-cmd:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: version
    networks:
      - internal
    entrypoint:
      - migrate
      - -path
      - /migrations/
      - -database
      - postgres://polkadothub:polkadothub@database:5432/polkadothub?sslmode=disable
    environment:
      DATABASE_DSN: postgres://polkadothub:polkadothub@database/polkadothub?sslmode=disable
    depends_on:
      - database