// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/figment-networks/polkadothub-indexer/store (interfaces: AccountEraSeq,BlockSeq,BlockSummary,Database,EventSeq,Reports,Syncables,ValidatorAgg,ValidatorEraSeq,ValidatorSessionSeq,ValidatorSummary)

// Package mock_store is a generated GoMock package.
package mock_store

import (
	model "github.com/figment-networks/polkadothub-indexer/model"
	store "github.com/figment-networks/polkadothub-indexer/store"
	types "github.com/figment-networks/polkadothub-indexer/types"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	time "time"
)

// MockAccountEraSeq is a mock of AccountEraSeq interface
type MockAccountEraSeq struct {
	ctrl     *gomock.Controller
	recorder *MockAccountEraSeqMockRecorder
}

// MockAccountEraSeqMockRecorder is the mock recorder for MockAccountEraSeq
type MockAccountEraSeqMockRecorder struct {
	mock *MockAccountEraSeq
}

// NewMockAccountEraSeq creates a new mock instance
func NewMockAccountEraSeq(ctrl *gomock.Controller) *MockAccountEraSeq {
	mock := &MockAccountEraSeq{ctrl: ctrl}
	mock.recorder = &MockAccountEraSeqMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAccountEraSeq) EXPECT() *MockAccountEraSeqMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockAccountEraSeq) Create(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockAccountEraSeqMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccountEraSeq)(nil).Create), arg0)
}

// DeleteOlderThan mocks base method
func (m *MockAccountEraSeq) DeleteOlderThan(arg0 time.Time) (*int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOlderThan", arg0)
	ret0, _ := ret[0].(*int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOlderThan indicates an expected call of DeleteOlderThan
func (mr *MockAccountEraSeqMockRecorder) DeleteOlderThan(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOlderThan", reflect.TypeOf((*MockAccountEraSeq)(nil).DeleteOlderThan), arg0)
}

// FindByEra mocks base method
func (m *MockAccountEraSeq) FindByEra(arg0 int64) ([]model.AccountEraSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEra", arg0)
	ret0, _ := ret[0].([]model.AccountEraSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEra indicates an expected call of FindByEra
func (mr *MockAccountEraSeqMockRecorder) FindByEra(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEra", reflect.TypeOf((*MockAccountEraSeq)(nil).FindByEra), arg0)
}

// FindByEraAndStashAccount mocks base method
func (m *MockAccountEraSeq) FindByEraAndStashAccount(arg0 int64, arg1 string) (*model.AccountEraSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEraAndStashAccount", arg0, arg1)
	ret0, _ := ret[0].(*model.AccountEraSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEraAndStashAccount indicates an expected call of FindByEraAndStashAccount
func (mr *MockAccountEraSeqMockRecorder) FindByEraAndStashAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEraAndStashAccount", reflect.TypeOf((*MockAccountEraSeq)(nil).FindByEraAndStashAccount), arg0, arg1)
}

// FindByEraAndStashAccounts mocks base method
func (m *MockAccountEraSeq) FindByEraAndStashAccounts(arg0 int64, arg1, arg2 string) (*model.AccountEraSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEraAndStashAccounts", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.AccountEraSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEraAndStashAccounts indicates an expected call of FindByEraAndStashAccounts
func (mr *MockAccountEraSeqMockRecorder) FindByEraAndStashAccounts(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEraAndStashAccounts", reflect.TypeOf((*MockAccountEraSeq)(nil).FindByEraAndStashAccounts), arg0, arg1, arg2)
}

// FindByHeight mocks base method
func (m *MockAccountEraSeq) FindByHeight(arg0 int64) ([]model.AccountEraSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHeight", arg0)
	ret0, _ := ret[0].([]model.AccountEraSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByHeight indicates an expected call of FindByHeight
func (mr *MockAccountEraSeqMockRecorder) FindByHeight(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHeight", reflect.TypeOf((*MockAccountEraSeq)(nil).FindByHeight), arg0)
}

// FindByHeightAndStashAccounts mocks base method
func (m *MockAccountEraSeq) FindByHeightAndStashAccounts(arg0 int64, arg1, arg2 string) (*model.AccountEraSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHeightAndStashAccounts", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.AccountEraSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByHeightAndStashAccounts indicates an expected call of FindByHeightAndStashAccounts
func (mr *MockAccountEraSeqMockRecorder) FindByHeightAndStashAccounts(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHeightAndStashAccounts", reflect.TypeOf((*MockAccountEraSeq)(nil).FindByHeightAndStashAccounts), arg0, arg1, arg2)
}

// FindLastByStashAccount mocks base method
func (m *MockAccountEraSeq) FindLastByStashAccount(arg0 string, arg1 int64) ([]model.AccountEraSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLastByStashAccount", arg0, arg1)
	ret0, _ := ret[0].([]model.AccountEraSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLastByStashAccount indicates an expected call of FindLastByStashAccount
func (mr *MockAccountEraSeqMockRecorder) FindLastByStashAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLastByStashAccount", reflect.TypeOf((*MockAccountEraSeq)(nil).FindLastByStashAccount), arg0, arg1)
}

// FindLastByValidatorStashAccount mocks base method
func (m *MockAccountEraSeq) FindLastByValidatorStashAccount(arg0 string, arg1 int64) ([]model.AccountEraSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLastByValidatorStashAccount", arg0, arg1)
	ret0, _ := ret[0].([]model.AccountEraSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLastByValidatorStashAccount indicates an expected call of FindLastByValidatorStashAccount
func (mr *MockAccountEraSeqMockRecorder) FindLastByValidatorStashAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLastByValidatorStashAccount", reflect.TypeOf((*MockAccountEraSeq)(nil).FindLastByValidatorStashAccount), arg0, arg1)
}

// FindMostRecent mocks base method
func (m *MockAccountEraSeq) FindMostRecent() (*model.AccountEraSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMostRecent")
	ret0, _ := ret[0].(*model.AccountEraSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMostRecent indicates an expected call of FindMostRecent
func (mr *MockAccountEraSeqMockRecorder) FindMostRecent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMostRecent", reflect.TypeOf((*MockAccountEraSeq)(nil).FindMostRecent))
}

// Save mocks base method
func (m *MockAccountEraSeq) Save(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save
func (mr *MockAccountEraSeqMockRecorder) Save(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAccountEraSeq)(nil).Save), arg0)
}

// Update mocks base method
func (m *MockAccountEraSeq) Update(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockAccountEraSeqMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAccountEraSeq)(nil).Update), arg0)
}

// MockBlockSeq is a mock of BlockSeq interface
type MockBlockSeq struct {
	ctrl     *gomock.Controller
	recorder *MockBlockSeqMockRecorder
}

// MockBlockSeqMockRecorder is the mock recorder for MockBlockSeq
type MockBlockSeqMockRecorder struct {
	mock *MockBlockSeq
}

// NewMockBlockSeq creates a new mock instance
func NewMockBlockSeq(ctrl *gomock.Controller) *MockBlockSeq {
	mock := &MockBlockSeq{ctrl: ctrl}
	mock.recorder = &MockBlockSeqMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBlockSeq) EXPECT() *MockBlockSeqMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockBlockSeq) Create(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockBlockSeqMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBlockSeq)(nil).Create), arg0)
}

// DeleteOlderThan mocks base method
func (m *MockBlockSeq) DeleteOlderThan(arg0 time.Time, arg1 []store.ActivityPeriodRow) (*int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOlderThan", arg0, arg1)
	ret0, _ := ret[0].(*int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOlderThan indicates an expected call of DeleteOlderThan
func (mr *MockBlockSeqMockRecorder) DeleteOlderThan(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOlderThan", reflect.TypeOf((*MockBlockSeq)(nil).DeleteOlderThan), arg0, arg1)
}

// FindByHeight mocks base method
func (m *MockBlockSeq) FindByHeight(arg0 int64) (*model.BlockSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHeight", arg0)
	ret0, _ := ret[0].(*model.BlockSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByHeight indicates an expected call of FindByHeight
func (mr *MockBlockSeqMockRecorder) FindByHeight(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHeight", reflect.TypeOf((*MockBlockSeq)(nil).FindByHeight), arg0)
}

// FindByID mocks base method
func (m *MockBlockSeq) FindByID(arg0 int64) (*model.BlockSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0)
	ret0, _ := ret[0].(*model.BlockSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID
func (mr *MockBlockSeqMockRecorder) FindByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockBlockSeq)(nil).FindByID), arg0)
}

// FindMostRecent mocks base method
func (m *MockBlockSeq) FindMostRecent() (*model.BlockSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMostRecent")
	ret0, _ := ret[0].(*model.BlockSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMostRecent indicates an expected call of FindMostRecent
func (mr *MockBlockSeqMockRecorder) FindMostRecent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMostRecent", reflect.TypeOf((*MockBlockSeq)(nil).FindMostRecent))
}

// GetAvgRecentTimes mocks base method
func (m *MockBlockSeq) GetAvgRecentTimes(arg0 int64) store.GetAvgRecentTimesResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvgRecentTimes", arg0)
	ret0, _ := ret[0].(store.GetAvgRecentTimesResult)
	return ret0
}

// GetAvgRecentTimes indicates an expected call of GetAvgRecentTimes
func (mr *MockBlockSeqMockRecorder) GetAvgRecentTimes(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvgRecentTimes", reflect.TypeOf((*MockBlockSeq)(nil).GetAvgRecentTimes), arg0)
}

// Save mocks base method
func (m *MockBlockSeq) Save(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save
func (mr *MockBlockSeqMockRecorder) Save(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockBlockSeq)(nil).Save), arg0)
}

// Summarize mocks base method
func (m *MockBlockSeq) Summarize(arg0 types.SummaryInterval, arg1 []store.ActivityPeriodRow) ([]store.BlockSeqSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Summarize", arg0, arg1)
	ret0, _ := ret[0].([]store.BlockSeqSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Summarize indicates an expected call of Summarize
func (mr *MockBlockSeqMockRecorder) Summarize(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summarize", reflect.TypeOf((*MockBlockSeq)(nil).Summarize), arg0, arg1)
}

// Update mocks base method
func (m *MockBlockSeq) Update(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockBlockSeqMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBlockSeq)(nil).Update), arg0)
}

// MockBlockSummary is a mock of BlockSummary interface
type MockBlockSummary struct {
	ctrl     *gomock.Controller
	recorder *MockBlockSummaryMockRecorder
}

// MockBlockSummaryMockRecorder is the mock recorder for MockBlockSummary
type MockBlockSummaryMockRecorder struct {
	mock *MockBlockSummary
}

// NewMockBlockSummary creates a new mock instance
func NewMockBlockSummary(ctrl *gomock.Controller) *MockBlockSummary {
	mock := &MockBlockSummary{ctrl: ctrl}
	mock.recorder = &MockBlockSummaryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBlockSummary) EXPECT() *MockBlockSummaryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockBlockSummary) Create(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockBlockSummaryMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBlockSummary)(nil).Create), arg0)
}

// DeleteOlderThan mocks base method
func (m *MockBlockSummary) DeleteOlderThan(arg0 types.SummaryInterval, arg1 time.Time) (*int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOlderThan", arg0, arg1)
	ret0, _ := ret[0].(*int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOlderThan indicates an expected call of DeleteOlderThan
func (mr *MockBlockSummaryMockRecorder) DeleteOlderThan(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOlderThan", reflect.TypeOf((*MockBlockSummary)(nil).DeleteOlderThan), arg0, arg1)
}

// Find mocks base method
func (m *MockBlockSummary) Find(arg0 *model.BlockSummary) (*model.BlockSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0)
	ret0, _ := ret[0].(*model.BlockSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find
func (mr *MockBlockSummaryMockRecorder) Find(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockBlockSummary)(nil).Find), arg0)
}

// FindActivityPeriods mocks base method
func (m *MockBlockSummary) FindActivityPeriods(arg0 types.SummaryInterval, arg1 int64) ([]store.ActivityPeriodRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActivityPeriods", arg0, arg1)
	ret0, _ := ret[0].([]store.ActivityPeriodRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActivityPeriods indicates an expected call of FindActivityPeriods
func (mr *MockBlockSummaryMockRecorder) FindActivityPeriods(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActivityPeriods", reflect.TypeOf((*MockBlockSummary)(nil).FindActivityPeriods), arg0, arg1)
}

// FindMostRecent mocks base method
func (m *MockBlockSummary) FindMostRecent() (*model.BlockSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMostRecent")
	ret0, _ := ret[0].(*model.BlockSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMostRecent indicates an expected call of FindMostRecent
func (mr *MockBlockSummaryMockRecorder) FindMostRecent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMostRecent", reflect.TypeOf((*MockBlockSummary)(nil).FindMostRecent))
}

// FindMostRecentByInterval mocks base method
func (m *MockBlockSummary) FindMostRecentByInterval(arg0 types.SummaryInterval) (*model.BlockSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMostRecentByInterval", arg0)
	ret0, _ := ret[0].(*model.BlockSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMostRecentByInterval indicates an expected call of FindMostRecentByInterval
func (mr *MockBlockSummaryMockRecorder) FindMostRecentByInterval(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMostRecentByInterval", reflect.TypeOf((*MockBlockSummary)(nil).FindMostRecentByInterval), arg0)
}

// FindSummary mocks base method
func (m *MockBlockSummary) FindSummary(arg0 types.SummaryInterval, arg1 string) ([]model.BlockSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSummary", arg0, arg1)
	ret0, _ := ret[0].([]model.BlockSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSummary indicates an expected call of FindSummary
func (mr *MockBlockSummaryMockRecorder) FindSummary(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSummary", reflect.TypeOf((*MockBlockSummary)(nil).FindSummary), arg0, arg1)
}

// Save mocks base method
func (m *MockBlockSummary) Save(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save
func (mr *MockBlockSummaryMockRecorder) Save(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockBlockSummary)(nil).Save), arg0)
}

// Update mocks base method
func (m *MockBlockSummary) Update(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockBlockSummaryMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBlockSummary)(nil).Update), arg0)
}

// MockDatabase is a mock of Database interface
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
}

// MockDatabaseMockRecorder is the mock recorder for MockDatabase
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

// NewMockDatabase creates a new mock instance
func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &MockDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDatabase) EXPECT() *MockDatabaseMockRecorder {
	return m.recorder
}

// GetTotalSize mocks base method
func (m *MockDatabase) GetTotalSize() (*store.GetTotalSizeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalSize")
	ret0, _ := ret[0].(*store.GetTotalSizeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalSize indicates an expected call of GetTotalSize
func (mr *MockDatabaseMockRecorder) GetTotalSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalSize", reflect.TypeOf((*MockDatabase)(nil).GetTotalSize))
}

// MockEventSeq is a mock of EventSeq interface
type MockEventSeq struct {
	ctrl     *gomock.Controller
	recorder *MockEventSeqMockRecorder
}

// MockEventSeqMockRecorder is the mock recorder for MockEventSeq
type MockEventSeqMockRecorder struct {
	mock *MockEventSeq
}

// NewMockEventSeq creates a new mock instance
func NewMockEventSeq(ctrl *gomock.Controller) *MockEventSeq {
	mock := &MockEventSeq{ctrl: ctrl}
	mock.recorder = &MockEventSeqMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockEventSeq) EXPECT() *MockEventSeqMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockEventSeq) Create(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockEventSeqMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEventSeq)(nil).Create), arg0)
}

// FindBalanceDeposits mocks base method
func (m *MockEventSeq) FindBalanceDeposits(arg0 string) ([]model.EventSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBalanceDeposits", arg0)
	ret0, _ := ret[0].([]model.EventSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBalanceDeposits indicates an expected call of FindBalanceDeposits
func (mr *MockEventSeqMockRecorder) FindBalanceDeposits(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBalanceDeposits", reflect.TypeOf((*MockEventSeq)(nil).FindBalanceDeposits), arg0)
}

// FindBalanceTransfers mocks base method
func (m *MockEventSeq) FindBalanceTransfers(arg0 string) ([]model.EventSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBalanceTransfers", arg0)
	ret0, _ := ret[0].([]model.EventSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBalanceTransfers indicates an expected call of FindBalanceTransfers
func (mr *MockEventSeqMockRecorder) FindBalanceTransfers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBalanceTransfers", reflect.TypeOf((*MockEventSeq)(nil).FindBalanceTransfers), arg0)
}

// FindBonded mocks base method
func (m *MockEventSeq) FindBonded(arg0 string) ([]model.EventSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBonded", arg0)
	ret0, _ := ret[0].([]model.EventSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBonded indicates an expected call of FindBonded
func (mr *MockEventSeqMockRecorder) FindBonded(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBonded", reflect.TypeOf((*MockEventSeq)(nil).FindBonded), arg0)
}

// FindByHeightAndIndex mocks base method
func (m *MockEventSeq) FindByHeightAndIndex(arg0, arg1 int64) (*model.EventSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHeightAndIndex", arg0, arg1)
	ret0, _ := ret[0].(*model.EventSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByHeightAndIndex indicates an expected call of FindByHeightAndIndex
func (mr *MockEventSeqMockRecorder) FindByHeightAndIndex(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHeightAndIndex", reflect.TypeOf((*MockEventSeq)(nil).FindByHeightAndIndex), arg0, arg1)
}

// FindUnbonded mocks base method
func (m *MockEventSeq) FindUnbonded(arg0 string) ([]model.EventSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUnbonded", arg0)
	ret0, _ := ret[0].([]model.EventSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUnbonded indicates an expected call of FindUnbonded
func (mr *MockEventSeqMockRecorder) FindUnbonded(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUnbonded", reflect.TypeOf((*MockEventSeq)(nil).FindUnbonded), arg0)
}

// FindWithdrawn mocks base method
func (m *MockEventSeq) FindWithdrawn(arg0 string) ([]model.EventSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithdrawn", arg0)
	ret0, _ := ret[0].([]model.EventSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWithdrawn indicates an expected call of FindWithdrawn
func (mr *MockEventSeqMockRecorder) FindWithdrawn(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithdrawn", reflect.TypeOf((*MockEventSeq)(nil).FindWithdrawn), arg0)
}

// Save mocks base method
func (m *MockEventSeq) Save(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save
func (mr *MockEventSeqMockRecorder) Save(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockEventSeq)(nil).Save), arg0)
}

// Update mocks base method
func (m *MockEventSeq) Update(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockEventSeqMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEventSeq)(nil).Update), arg0)
}

// MockReports is a mock of Reports interface
type MockReports struct {
	ctrl     *gomock.Controller
	recorder *MockReportsMockRecorder
}

// MockReportsMockRecorder is the mock recorder for MockReports
type MockReportsMockRecorder struct {
	mock *MockReports
}

// NewMockReports creates a new mock instance
func NewMockReports(ctrl *gomock.Controller) *MockReports {
	mock := &MockReports{ctrl: ctrl}
	mock.recorder = &MockReportsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockReports) EXPECT() *MockReportsMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockReports) Create(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockReportsMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReports)(nil).Create), arg0)
}

// DeleteByKinds mocks base method
func (m *MockReports) DeleteByKinds(arg0 []model.ReportKind) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByKinds", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByKinds indicates an expected call of DeleteByKinds
func (mr *MockReportsMockRecorder) DeleteByKinds(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByKinds", reflect.TypeOf((*MockReports)(nil).DeleteByKinds), arg0)
}

// FindNotCompletedByIndexVersion mocks base method
func (m *MockReports) FindNotCompletedByIndexVersion(arg0 int64, arg1 ...model.ReportKind) (*model.Report, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindNotCompletedByIndexVersion", varargs...)
	ret0, _ := ret[0].(*model.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNotCompletedByIndexVersion indicates an expected call of FindNotCompletedByIndexVersion
func (mr *MockReportsMockRecorder) FindNotCompletedByIndexVersion(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNotCompletedByIndexVersion", reflect.TypeOf((*MockReports)(nil).FindNotCompletedByIndexVersion), varargs...)
}

// FindNotCompletedByKind mocks base method
func (m *MockReports) FindNotCompletedByKind(arg0 ...model.ReportKind) (*model.Report, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindNotCompletedByKind", varargs...)
	ret0, _ := ret[0].(*model.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNotCompletedByKind indicates an expected call of FindNotCompletedByKind
func (mr *MockReportsMockRecorder) FindNotCompletedByKind(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNotCompletedByKind", reflect.TypeOf((*MockReports)(nil).FindNotCompletedByKind), arg0...)
}

// Last mocks base method
func (m *MockReports) Last() (*model.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Last")
	ret0, _ := ret[0].(*model.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Last indicates an expected call of Last
func (mr *MockReportsMockRecorder) Last() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Last", reflect.TypeOf((*MockReports)(nil).Last))
}

// Save mocks base method
func (m *MockReports) Save(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save
func (mr *MockReportsMockRecorder) Save(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockReports)(nil).Save), arg0)
}

// Update mocks base method
func (m *MockReports) Update(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockReportsMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockReports)(nil).Update), arg0)
}

// MockSyncables is a mock of Syncables interface
type MockSyncables struct {
	ctrl     *gomock.Controller
	recorder *MockSyncablesMockRecorder
}

// MockSyncablesMockRecorder is the mock recorder for MockSyncables
type MockSyncablesMockRecorder struct {
	mock *MockSyncables
}

// NewMockSyncables creates a new mock instance
func NewMockSyncables(ctrl *gomock.Controller) *MockSyncables {
	mock := &MockSyncables{ctrl: ctrl}
	mock.recorder = &MockSyncablesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSyncables) EXPECT() *MockSyncablesMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockSyncables) Create(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockSyncablesMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSyncables)(nil).Create), arg0)
}

// CreateOrUpdate mocks base method
func (m *MockSyncables) CreateOrUpdate(arg0 *model.Syncable) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdate indicates an expected call of CreateOrUpdate
func (mr *MockSyncablesMockRecorder) CreateOrUpdate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdate", reflect.TypeOf((*MockSyncables)(nil).CreateOrUpdate), arg0)
}

// FindByHeight mocks base method
func (m *MockSyncables) FindByHeight(arg0 int64) (*model.Syncable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHeight", arg0)
	ret0, _ := ret[0].(*model.Syncable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByHeight indicates an expected call of FindByHeight
func (mr *MockSyncablesMockRecorder) FindByHeight(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHeight", reflect.TypeOf((*MockSyncables)(nil).FindByHeight), arg0)
}

// FindFirstByDifferentIndexVersion mocks base method
func (m *MockSyncables) FindFirstByDifferentIndexVersion(arg0 int64) (*model.Syncable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFirstByDifferentIndexVersion", arg0)
	ret0, _ := ret[0].(*model.Syncable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFirstByDifferentIndexVersion indicates an expected call of FindFirstByDifferentIndexVersion
func (mr *MockSyncablesMockRecorder) FindFirstByDifferentIndexVersion(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFirstByDifferentIndexVersion", reflect.TypeOf((*MockSyncables)(nil).FindFirstByDifferentIndexVersion), arg0)
}

// FindLastInEra mocks base method
func (m *MockSyncables) FindLastInEra(arg0 int64) (*model.Syncable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLastInEra", arg0)
	ret0, _ := ret[0].(*model.Syncable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLastInEra indicates an expected call of FindLastInEra
func (mr *MockSyncablesMockRecorder) FindLastInEra(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLastInEra", reflect.TypeOf((*MockSyncables)(nil).FindLastInEra), arg0)
}

// FindLastInSession mocks base method
func (m *MockSyncables) FindLastInSession(arg0 int64) (*model.Syncable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLastInSession", arg0)
	ret0, _ := ret[0].(*model.Syncable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLastInSession indicates an expected call of FindLastInSession
func (mr *MockSyncablesMockRecorder) FindLastInSession(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLastInSession", reflect.TypeOf((*MockSyncables)(nil).FindLastInSession), arg0)
}

// FindMostRecent mocks base method
func (m *MockSyncables) FindMostRecent() (*model.Syncable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMostRecent")
	ret0, _ := ret[0].(*model.Syncable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMostRecent indicates an expected call of FindMostRecent
func (mr *MockSyncablesMockRecorder) FindMostRecent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMostRecent", reflect.TypeOf((*MockSyncables)(nil).FindMostRecent))
}

// FindMostRecentByDifferentIndexVersion mocks base method
func (m *MockSyncables) FindMostRecentByDifferentIndexVersion(arg0 int64) (*model.Syncable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMostRecentByDifferentIndexVersion", arg0)
	ret0, _ := ret[0].(*model.Syncable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMostRecentByDifferentIndexVersion indicates an expected call of FindMostRecentByDifferentIndexVersion
func (mr *MockSyncablesMockRecorder) FindMostRecentByDifferentIndexVersion(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMostRecentByDifferentIndexVersion", reflect.TypeOf((*MockSyncables)(nil).FindMostRecentByDifferentIndexVersion), arg0)
}

// FindSmallestIndexVersion mocks base method
func (m *MockSyncables) FindSmallestIndexVersion() (*int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSmallestIndexVersion")
	ret0, _ := ret[0].(*int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSmallestIndexVersion indicates an expected call of FindSmallestIndexVersion
func (mr *MockSyncablesMockRecorder) FindSmallestIndexVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSmallestIndexVersion", reflect.TypeOf((*MockSyncables)(nil).FindSmallestIndexVersion))
}

// Save mocks base method
func (m *MockSyncables) Save(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save
func (mr *MockSyncablesMockRecorder) Save(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSyncables)(nil).Save), arg0)
}

// SetProcessedAtForRange mocks base method
func (m *MockSyncables) SetProcessedAtForRange(arg0 types.ID, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProcessedAtForRange", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProcessedAtForRange indicates an expected call of SetProcessedAtForRange
func (mr *MockSyncablesMockRecorder) SetProcessedAtForRange(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProcessedAtForRange", reflect.TypeOf((*MockSyncables)(nil).SetProcessedAtForRange), arg0, arg1, arg2)
}

// Update mocks base method
func (m *MockSyncables) Update(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockSyncablesMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSyncables)(nil).Update), arg0)
}

// MockValidatorAgg is a mock of ValidatorAgg interface
type MockValidatorAgg struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorAggMockRecorder
}

// MockValidatorAggMockRecorder is the mock recorder for MockValidatorAgg
type MockValidatorAggMockRecorder struct {
	mock *MockValidatorAgg
}

// NewMockValidatorAgg creates a new mock instance
func NewMockValidatorAgg(ctrl *gomock.Controller) *MockValidatorAgg {
	mock := &MockValidatorAgg{ctrl: ctrl}
	mock.recorder = &MockValidatorAggMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockValidatorAgg) EXPECT() *MockValidatorAggMockRecorder {
	return m.recorder
}

// All mocks base method
func (m *MockValidatorAgg) All() ([]model.ValidatorAgg, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All")
	ret0, _ := ret[0].([]model.ValidatorAgg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// All indicates an expected call of All
func (mr *MockValidatorAggMockRecorder) All() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockValidatorAgg)(nil).All))
}

// Create mocks base method
func (m *MockValidatorAgg) Create(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockValidatorAggMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockValidatorAgg)(nil).Create), arg0)
}

// CreateOrUpdate mocks base method
func (m *MockValidatorAgg) CreateOrUpdate(arg0 *model.ValidatorAgg) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdate indicates an expected call of CreateOrUpdate
func (mr *MockValidatorAggMockRecorder) CreateOrUpdate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdate", reflect.TypeOf((*MockValidatorAgg)(nil).CreateOrUpdate), arg0)
}

// FindBy mocks base method
func (m *MockValidatorAgg) FindBy(arg0 string, arg1 interface{}) (*model.ValidatorAgg, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBy", arg0, arg1)
	ret0, _ := ret[0].(*model.ValidatorAgg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBy indicates an expected call of FindBy
func (mr *MockValidatorAggMockRecorder) FindBy(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBy", reflect.TypeOf((*MockValidatorAgg)(nil).FindBy), arg0, arg1)
}

// FindByID mocks base method
func (m *MockValidatorAgg) FindByID(arg0 int64) (*model.ValidatorAgg, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0)
	ret0, _ := ret[0].(*model.ValidatorAgg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID
func (mr *MockValidatorAggMockRecorder) FindByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockValidatorAgg)(nil).FindByID), arg0)
}

// FindByStashAccount mocks base method
func (m *MockValidatorAgg) FindByStashAccount(arg0 string) (*model.ValidatorAgg, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByStashAccount", arg0)
	ret0, _ := ret[0].(*model.ValidatorAgg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByStashAccount indicates an expected call of FindByStashAccount
func (mr *MockValidatorAggMockRecorder) FindByStashAccount(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByStashAccount", reflect.TypeOf((*MockValidatorAgg)(nil).FindByStashAccount), arg0)
}

// GetAllForHeightGreaterThan mocks base method
func (m *MockValidatorAgg) GetAllForHeightGreaterThan(arg0 int64) ([]model.ValidatorAgg, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllForHeightGreaterThan", arg0)
	ret0, _ := ret[0].([]model.ValidatorAgg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllForHeightGreaterThan indicates an expected call of GetAllForHeightGreaterThan
func (mr *MockValidatorAggMockRecorder) GetAllForHeightGreaterThan(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllForHeightGreaterThan", reflect.TypeOf((*MockValidatorAgg)(nil).GetAllForHeightGreaterThan), arg0)
}

// Save mocks base method
func (m *MockValidatorAgg) Save(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save
func (mr *MockValidatorAggMockRecorder) Save(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockValidatorAgg)(nil).Save), arg0)
}

// Update mocks base method
func (m *MockValidatorAgg) Update(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockValidatorAggMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockValidatorAgg)(nil).Update), arg0)
}

// MockValidatorEraSeq is a mock of ValidatorEraSeq interface
type MockValidatorEraSeq struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorEraSeqMockRecorder
}

// MockValidatorEraSeqMockRecorder is the mock recorder for MockValidatorEraSeq
type MockValidatorEraSeqMockRecorder struct {
	mock *MockValidatorEraSeq
}

// NewMockValidatorEraSeq creates a new mock instance
func NewMockValidatorEraSeq(ctrl *gomock.Controller) *MockValidatorEraSeq {
	mock := &MockValidatorEraSeq{ctrl: ctrl}
	mock.recorder = &MockValidatorEraSeqMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockValidatorEraSeq) EXPECT() *MockValidatorEraSeqMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockValidatorEraSeq) Create(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockValidatorEraSeqMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockValidatorEraSeq)(nil).Create), arg0)
}

// CreateIfNotExists mocks base method
func (m *MockValidatorEraSeq) CreateIfNotExists(arg0 *model.ValidatorEraSeq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIfNotExists", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIfNotExists indicates an expected call of CreateIfNotExists
func (mr *MockValidatorEraSeqMockRecorder) CreateIfNotExists(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIfNotExists", reflect.TypeOf((*MockValidatorEraSeq)(nil).CreateIfNotExists), arg0)
}

// DeleteOlderThan mocks base method
func (m *MockValidatorEraSeq) DeleteOlderThan(arg0 time.Time) (*int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOlderThan", arg0)
	ret0, _ := ret[0].(*int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOlderThan indicates an expected call of DeleteOlderThan
func (mr *MockValidatorEraSeqMockRecorder) DeleteOlderThan(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOlderThan", reflect.TypeOf((*MockValidatorEraSeq)(nil).DeleteOlderThan), arg0)
}

// FindByEra mocks base method
func (m *MockValidatorEraSeq) FindByEra(arg0 int64) ([]model.ValidatorEraSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEra", arg0)
	ret0, _ := ret[0].([]model.ValidatorEraSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEra indicates an expected call of FindByEra
func (mr *MockValidatorEraSeqMockRecorder) FindByEra(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEra", reflect.TypeOf((*MockValidatorEraSeq)(nil).FindByEra), arg0)
}

// FindByEraAndStashAccount mocks base method
func (m *MockValidatorEraSeq) FindByEraAndStashAccount(arg0 int64, arg1 string) (*model.ValidatorEraSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEraAndStashAccount", arg0, arg1)
	ret0, _ := ret[0].(*model.ValidatorEraSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEraAndStashAccount indicates an expected call of FindByEraAndStashAccount
func (mr *MockValidatorEraSeqMockRecorder) FindByEraAndStashAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEraAndStashAccount", reflect.TypeOf((*MockValidatorEraSeq)(nil).FindByEraAndStashAccount), arg0, arg1)
}

// FindByHeight mocks base method
func (m *MockValidatorEraSeq) FindByHeight(arg0 int64) ([]model.ValidatorEraSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHeight", arg0)
	ret0, _ := ret[0].([]model.ValidatorEraSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByHeight indicates an expected call of FindByHeight
func (mr *MockValidatorEraSeqMockRecorder) FindByHeight(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHeight", reflect.TypeOf((*MockValidatorEraSeq)(nil).FindByHeight), arg0)
}

// FindByHeightAndStashAccount mocks base method
func (m *MockValidatorEraSeq) FindByHeightAndStashAccount(arg0 int64, arg1 string) (*model.ValidatorEraSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHeightAndStashAccount", arg0, arg1)
	ret0, _ := ret[0].(*model.ValidatorEraSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByHeightAndStashAccount indicates an expected call of FindByHeightAndStashAccount
func (mr *MockValidatorEraSeqMockRecorder) FindByHeightAndStashAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHeightAndStashAccount", reflect.TypeOf((*MockValidatorEraSeq)(nil).FindByHeightAndStashAccount), arg0, arg1)
}

// FindLastByStashAccount mocks base method
func (m *MockValidatorEraSeq) FindLastByStashAccount(arg0 string, arg1 int64) ([]model.ValidatorEraSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLastByStashAccount", arg0, arg1)
	ret0, _ := ret[0].([]model.ValidatorEraSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLastByStashAccount indicates an expected call of FindLastByStashAccount
func (mr *MockValidatorEraSeqMockRecorder) FindLastByStashAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLastByStashAccount", reflect.TypeOf((*MockValidatorEraSeq)(nil).FindLastByStashAccount), arg0, arg1)
}

// FindMostRecent mocks base method
func (m *MockValidatorEraSeq) FindMostRecent() (*model.ValidatorEraSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMostRecent")
	ret0, _ := ret[0].(*model.ValidatorEraSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMostRecent indicates an expected call of FindMostRecent
func (mr *MockValidatorEraSeqMockRecorder) FindMostRecent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMostRecent", reflect.TypeOf((*MockValidatorEraSeq)(nil).FindMostRecent))
}

// Save mocks base method
func (m *MockValidatorEraSeq) Save(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save
func (mr *MockValidatorEraSeqMockRecorder) Save(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockValidatorEraSeq)(nil).Save), arg0)
}

// Summarize mocks base method
func (m *MockValidatorEraSeq) Summarize(arg0 types.SummaryInterval, arg1 []store.ActivityPeriodRow) ([]store.ValidatorEraSeqSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Summarize", arg0, arg1)
	ret0, _ := ret[0].([]store.ValidatorEraSeqSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Summarize indicates an expected call of Summarize
func (mr *MockValidatorEraSeqMockRecorder) Summarize(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summarize", reflect.TypeOf((*MockValidatorEraSeq)(nil).Summarize), arg0, arg1)
}

// Update mocks base method
func (m *MockValidatorEraSeq) Update(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockValidatorEraSeqMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockValidatorEraSeq)(nil).Update), arg0)
}

// MockValidatorSessionSeq is a mock of ValidatorSessionSeq interface
type MockValidatorSessionSeq struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorSessionSeqMockRecorder
}

// MockValidatorSessionSeqMockRecorder is the mock recorder for MockValidatorSessionSeq
type MockValidatorSessionSeqMockRecorder struct {
	mock *MockValidatorSessionSeq
}

// NewMockValidatorSessionSeq creates a new mock instance
func NewMockValidatorSessionSeq(ctrl *gomock.Controller) *MockValidatorSessionSeq {
	mock := &MockValidatorSessionSeq{ctrl: ctrl}
	mock.recorder = &MockValidatorSessionSeqMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockValidatorSessionSeq) EXPECT() *MockValidatorSessionSeqMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockValidatorSessionSeq) Create(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockValidatorSessionSeqMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockValidatorSessionSeq)(nil).Create), arg0)
}

// DeleteOlderThan mocks base method
func (m *MockValidatorSessionSeq) DeleteOlderThan(arg0 time.Time) (*int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOlderThan", arg0)
	ret0, _ := ret[0].(*int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOlderThan indicates an expected call of DeleteOlderThan
func (mr *MockValidatorSessionSeqMockRecorder) DeleteOlderThan(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOlderThan", reflect.TypeOf((*MockValidatorSessionSeq)(nil).DeleteOlderThan), arg0)
}

// FindByHeight mocks base method
func (m *MockValidatorSessionSeq) FindByHeight(arg0 int64) ([]model.ValidatorSessionSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHeight", arg0)
	ret0, _ := ret[0].([]model.ValidatorSessionSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByHeight indicates an expected call of FindByHeight
func (mr *MockValidatorSessionSeqMockRecorder) FindByHeight(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHeight", reflect.TypeOf((*MockValidatorSessionSeq)(nil).FindByHeight), arg0)
}

// FindBySessionAndStashAccount mocks base method
func (m *MockValidatorSessionSeq) FindBySessionAndStashAccount(arg0 int64, arg1 string) (*model.ValidatorSessionSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySessionAndStashAccount", arg0, arg1)
	ret0, _ := ret[0].(*model.ValidatorSessionSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySessionAndStashAccount indicates an expected call of FindBySessionAndStashAccount
func (mr *MockValidatorSessionSeqMockRecorder) FindBySessionAndStashAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySessionAndStashAccount", reflect.TypeOf((*MockValidatorSessionSeq)(nil).FindBySessionAndStashAccount), arg0, arg1)
}

// FindLastByStashAccount mocks base method
func (m *MockValidatorSessionSeq) FindLastByStashAccount(arg0 string, arg1 int64) ([]model.ValidatorSessionSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLastByStashAccount", arg0, arg1)
	ret0, _ := ret[0].([]model.ValidatorSessionSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLastByStashAccount indicates an expected call of FindLastByStashAccount
func (mr *MockValidatorSessionSeqMockRecorder) FindLastByStashAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLastByStashAccount", reflect.TypeOf((*MockValidatorSessionSeq)(nil).FindLastByStashAccount), arg0, arg1)
}

// FindMostRecent mocks base method
func (m *MockValidatorSessionSeq) FindMostRecent() (*model.ValidatorSessionSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMostRecent")
	ret0, _ := ret[0].(*model.ValidatorSessionSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMostRecent indicates an expected call of FindMostRecent
func (mr *MockValidatorSessionSeqMockRecorder) FindMostRecent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMostRecent", reflect.TypeOf((*MockValidatorSessionSeq)(nil).FindMostRecent))
}

// Save mocks base method
func (m *MockValidatorSessionSeq) Save(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save
func (mr *MockValidatorSessionSeqMockRecorder) Save(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockValidatorSessionSeq)(nil).Save), arg0)
}

// Summarize mocks base method
func (m *MockValidatorSessionSeq) Summarize(arg0 types.SummaryInterval, arg1 []store.ActivityPeriodRow) ([]store.ValidatorSessionSeqSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Summarize", arg0, arg1)
	ret0, _ := ret[0].([]store.ValidatorSessionSeqSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Summarize indicates an expected call of Summarize
func (mr *MockValidatorSessionSeqMockRecorder) Summarize(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summarize", reflect.TypeOf((*MockValidatorSessionSeq)(nil).Summarize), arg0, arg1)
}

// Update mocks base method
func (m *MockValidatorSessionSeq) Update(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockValidatorSessionSeqMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockValidatorSessionSeq)(nil).Update), arg0)
}

// MockValidatorSummary is a mock of ValidatorSummary interface
type MockValidatorSummary struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorSummaryMockRecorder
}

// MockValidatorSummaryMockRecorder is the mock recorder for MockValidatorSummary
type MockValidatorSummaryMockRecorder struct {
	mock *MockValidatorSummary
}

// NewMockValidatorSummary creates a new mock instance
func NewMockValidatorSummary(ctrl *gomock.Controller) *MockValidatorSummary {
	mock := &MockValidatorSummary{ctrl: ctrl}
	mock.recorder = &MockValidatorSummaryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockValidatorSummary) EXPECT() *MockValidatorSummaryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockValidatorSummary) Create(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockValidatorSummaryMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockValidatorSummary)(nil).Create), arg0)
}

// DeleteOlderThan mocks base method
func (m *MockValidatorSummary) DeleteOlderThan(arg0 types.SummaryInterval, arg1 time.Time) (*int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOlderThan", arg0, arg1)
	ret0, _ := ret[0].(*int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOlderThan indicates an expected call of DeleteOlderThan
func (mr *MockValidatorSummaryMockRecorder) DeleteOlderThan(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOlderThan", reflect.TypeOf((*MockValidatorSummary)(nil).DeleteOlderThan), arg0, arg1)
}

// Find mocks base method
func (m *MockValidatorSummary) Find(arg0 *model.ValidatorSummary) (*model.ValidatorSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0)
	ret0, _ := ret[0].(*model.ValidatorSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find
func (mr *MockValidatorSummaryMockRecorder) Find(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockValidatorSummary)(nil).Find), arg0)
}

// FindActivityPeriods mocks base method
func (m *MockValidatorSummary) FindActivityPeriods(arg0 types.SummaryInterval, arg1 int64) ([]store.ActivityPeriodRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActivityPeriods", arg0, arg1)
	ret0, _ := ret[0].([]store.ActivityPeriodRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActivityPeriods indicates an expected call of FindActivityPeriods
func (mr *MockValidatorSummaryMockRecorder) FindActivityPeriods(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActivityPeriods", reflect.TypeOf((*MockValidatorSummary)(nil).FindActivityPeriods), arg0, arg1)
}

// FindMostRecent mocks base method
func (m *MockValidatorSummary) FindMostRecent() (*model.ValidatorSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMostRecent")
	ret0, _ := ret[0].(*model.ValidatorSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMostRecent indicates an expected call of FindMostRecent
func (mr *MockValidatorSummaryMockRecorder) FindMostRecent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMostRecent", reflect.TypeOf((*MockValidatorSummary)(nil).FindMostRecent))
}

// FindMostRecentByInterval mocks base method
func (m *MockValidatorSummary) FindMostRecentByInterval(arg0 types.SummaryInterval) (*model.ValidatorSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMostRecentByInterval", arg0)
	ret0, _ := ret[0].(*model.ValidatorSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMostRecentByInterval indicates an expected call of FindMostRecentByInterval
func (mr *MockValidatorSummaryMockRecorder) FindMostRecentByInterval(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMostRecentByInterval", reflect.TypeOf((*MockValidatorSummary)(nil).FindMostRecentByInterval), arg0)
}

// FindSummary mocks base method
func (m *MockValidatorSummary) FindSummary(arg0 types.SummaryInterval, arg1 string) ([]store.ValidatorSummaryRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSummary", arg0, arg1)
	ret0, _ := ret[0].([]store.ValidatorSummaryRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSummary indicates an expected call of FindSummary
func (mr *MockValidatorSummaryMockRecorder) FindSummary(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSummary", reflect.TypeOf((*MockValidatorSummary)(nil).FindSummary), arg0, arg1)
}

// FindSummaryByStashAccount mocks base method
func (m *MockValidatorSummary) FindSummaryByStashAccount(arg0 string, arg1 types.SummaryInterval, arg2 string) ([]model.ValidatorSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSummaryByStashAccount", arg0, arg1, arg2)
	ret0, _ := ret[0].([]model.ValidatorSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSummaryByStashAccount indicates an expected call of FindSummaryByStashAccount
func (mr *MockValidatorSummaryMockRecorder) FindSummaryByStashAccount(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSummaryByStashAccount", reflect.TypeOf((*MockValidatorSummary)(nil).FindSummaryByStashAccount), arg0, arg1, arg2)
}

// Save mocks base method
func (m *MockValidatorSummary) Save(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save
func (mr *MockValidatorSummaryMockRecorder) Save(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockValidatorSummary)(nil).Save), arg0)
}

// Update mocks base method
func (m *MockValidatorSummary) Update(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockValidatorSummaryMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockValidatorSummary)(nil).Update), arg0)
}
